// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PureMedBlockChain_Backend.Data;

namespace PureMedBlockChain_Backend.Migrations
{
    [DbContext(typeof(BlockChainsDbContext))]
    partial class BlockChainsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("PureMedBlockChain_Backend.Models.StoreBlockChains", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Difficulty");

                    b.Property<string>("PureMedBlockChain");

                    b.Property<string>("Verifier_1BlockChain");

                    b.Property<string>("Verifier_2BlockChain");

                    b.Property<string>("Verifier_3BlockChain");

                    b.HasKey("ID");

                    b.ToTable("AllBlockChains");
                });
#pragma warning restore 612, 618
        }
    }
}
